# Generated by Django 5.2.3 on 2025-07-22 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards_app', '0006_boarddetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boarddetail',
            old_name='owner',
            new_name='owner_id',
        ),
    ]
