# Generated by Django 5.2.3 on 2025-08-05 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_app', '0006_alter_userprofile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='password',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='repeated_password',
        ),
    ]
