# Generated by Django 5.2.3 on 2025-08-05 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_app', '0007_remove_userprofile_password_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
