# Generated by Django 5.2.3 on 2025-07-24 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0007_alter_task_assignee_alter_task_reviewer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tasks_app.task'),
        ),
    ]
