# Generated by Django 5.2.3 on 2025-07-24 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0010_remove_comment_task_alter_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='task',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tasks_app.task'),
            preserve_default=False,
        ),
    ]
