# Generated by Django 5.2.3 on 2025-08-04 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards_app', '0014_remove_boarddetail_tasks_alter_boarddetail_members'),
        ('tasks_app', '0011_comment_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='boards_app.board'),
        ),
    ]
