# Generated by Django 5.2.3 on 2025-08-04 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '__first__'),
        ('tasks_app', '0012_alter_task_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tasks_app.Task'),
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
