# Generated by Django 5.2.3 on 2025-08-04 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0014_task_alter_comment_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
