# Generated by Django 5.2.3 on 2025-08-06 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0016_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='comments_count',
            field=models.IntegerField(default=0),
        ),
    ]
