# Generated by Django 5.2.3 on 2025-07-22 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boards_app', '0007_rename_owner_boarddetail_owner_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(max_length=255)),
                ('priority', models.CharField(max_length=255)),
                ('due_date', models.DateField()),
                ('comments_count', models.IntegerField(default=0)),
                ('assignee_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to='boards_app.member')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards_app.board')),
                ('reviewer_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewing_tasks', to='boards_app.member')),
            ],
        ),
    ]
