# Generated by Django 5.2.3 on 2025-07-22 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='assignee_id',
            new_name='assignee',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='reviewer_id',
            new_name='reviewer',
        ),
    ]
