# Generated by Django 5.2.3 on 2025-07-17 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards_app', '0002_board_members_alter_board_member_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
