# Generated by Django 5.2.3 on 2025-07-18 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards_app', '0003_rename_owner_id_board_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('fullname', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='boarddetail',
            name='board',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='boards_app.board'),
        ),
        migrations.AddField(
            model_name='boarddetail',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='boarddetail',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='boards_detail', to='boards_app.member'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('status', models.CharField(max_length=20)),
                ('priority', models.CharField(max_length=10)),
                ('due_date', models.DateField()),
                ('comments_count', models.IntegerField()),
                ('assignee', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to='boards_app.member')),
                ('reviewer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewing_tasks', to='boards_app.member')),
            ],
        ),
        migrations.AddField(
            model_name='boarddetail',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='boards_tasks', to='boards_app.task'),
        ),
    ]
