# Generated by Django 5.2.3 on 2025-07-18 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards_app', '0004_member_boarddetail_board_boarddetail_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assignee',
        ),
        migrations.RemoveField(
            model_name='task',
            name='reviewer',
        ),
        migrations.DeleteModel(
            name='BoardDetail',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
