# Generated by Django 5.2.3 on 2025-07-22 11:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards_app', '0007_rename_owner_boarddetail_owner_id'),
        ('tasks_app', '0003_alter_task_assignee_alter_task_reviewer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.AlterField(
            model_name='boarddetail',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='boards_detail', to=settings.AUTH_USER_MODEL),
        ),
    ]
