# Generated by Django 5.2.3 on 2025-07-31 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards_app', '0008_delete_member_alter_boarddetail_members'),
        ('tasks_app', '0011_comment_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='boarddetail',
            name='tasks',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='tasks_app.task'),
            preserve_default=False,
        ),
    ]
