# Generated by Django 5.2.3 on 2025-07-31 10:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards_app', '0009_boarddetail_tasks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, related_name='boards', to=settings.AUTH_USER_MODEL),
        ),
    ]
