# Generated by Django 5.2.3 on 2025-07-31 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards_app', '0010_alter_board_members'),
        ('tasks_app', '0011_comment_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='tickets',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='board_tickets', to='tasks_app.task'),
            preserve_default=False,
        ),
    ]
