# Generated by Django 5.2.3 on 2025-07-31 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards_app', '0011_board_tickets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='tickets',
        ),
    ]
