# Generated by Django 5.2.3 on 2025-08-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards_app', '0012_remove_board_tickets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='tasks_high_prio_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='tasks_to_do_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='ticket_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
