# Generated by Django 5.2.3 on 2025-08-04 10:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards_app', '0013_alter_board_tasks_high_prio_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boarddetail',
            name='tasks',
        ),
        migrations.AlterField(
            model_name='boarddetail',
            name='members',
            field=models.ManyToManyField(related_name='boards_detail', to=settings.AUTH_USER_MODEL),
        ),
    ]
