# Generated by Django 5.2.3 on 2025-08-04 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards_app', '0014_remove_boarddetail_tasks_alter_boarddetail_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='members',
        ),
        migrations.RemoveField(
            model_name='board',
            name='owner',
        ),
    ]
