# Generated by Django 5.2.3 on 2025-08-04 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards_app', '0015_remove_board_members_remove_board_owner'),
        ('tasks_app', '0013_alter_comment_task_delete_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Board',
        ),
    ]
