# Generated by Django 5.2.3 on 2025-08-04 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards_app', '0016_delete_board'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('member_count', models.PositiveIntegerField(default=0)),
                ('ticket_count', models.IntegerField(blank=True, default=0, null=True)),
                ('tasks_to_do_count', models.IntegerField(blank=True, default=0, null=True)),
                ('tasks_high_prio_count', models.IntegerField(blank=True, default=0, null=True)),
                ('members', models.ManyToManyField(blank=True, null=True, related_name='boards', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
